### PR TITLE
URL Encode query string

### PR DESCRIPTION
**Pull request by epbensimpson**
Fix for #59

Not sure how to write a unit test for this as the client isn't very unit testable, but here's a dotnetfiddle link that demonstrates the problem and fix: https://dotnetfiddle.net/LL3IuP

### CODE REVIEW

**Comment by epbensimpson** [comment]
Looks like this implementation would regress #22, will take a look at doing this differently.

**Comment by robotdan** [comment]
Looks reasonable, hard to believe we have never seen this error come up before. @mooreds any opinion?

**Comment by mooreds** [comment]
This looks good to me. Merging.

**Comment by robotdan** [comment]
Thanks @epbensimpson !!

**Pull request merged**
