### PR TITLE
Add .net standard 2.0 support to library

### PR DESCRIPTION
**Pull request by lukevp**
- Update Patch method in DefaultRESTClient to build a PATCH request manually instead of using PatchAsync helper (doesn't exist in .net standard 2.0)

- Add netstandard2.0 to supported framework list so library can be used with full framework .NET

### CODE REVIEW

**Comment by robotdan** [comment]
@tyduptyler13 or @matthew-altman do you have an opinions on this? 

Looks like we are currently targeting std 2.1, core 3.1 and core 2.1. 

```
<TargetFrameworks>netstandard2.1;netcoreapp3.1;netcoreapp2.1</TargetFrameworks>
```

@lukevp You mentioned in https://github.com/FusionAuth/fusionauth-netcore-client/issues/13#issuecomment-592324073 a way to get around the missing `PatchAsync` method?

**Comment by tyduptyler13** [comment]
I'm not sure if we still need this. I recently added standard2.1 and it has patchAsync. Could you please let us know if you explicitly need standard2.0?

**Comment by lukevp** [comment]
@tyduptyler13  I don't personally need any of the netstandard versions since I'm building a new .net core 3 app anyway.  But net standard 2.1 is not backwards compatible with full framework apps.  Right now the migration path for users of Full Framework apps is to upgrade their whole app to run on .net core, which is not doable for everyone with larger apps. This means anyone with legacy apps must switch runtimes, whereas with this PR they can keep using full framework.  It's about backwards compatibility.  Net Standard 2 and 2.1 are significantly different in that regard.  Please see here: 
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

4.6.1 up to 4.8 are the full framework versions.

One example of an application is Telerik SiteFinity, we use this as a CMS at a company I work for, and it does not have a .net core version available at all, so it must run on the full framework runtime.

**Comment by lukevp** [comment]
Didn't mention this in previous comment but this would also make it so you did not have to maintain 2 versions of the .net client, since this one would work for both .net core and full framework apps back to 4.6.1.  You could retire the other client then.

**Comment by robotdan** [comment]
@tyduptyler13 if you don't have any other reservations I'll try merging this in and see if everything still builds and passes, etc.

**Comment by tyduptyler13** [comment]
> @tyduptyler13 if you don't have any other reservations I'll try merging this in and see if everything still builds and passes, etc.

Sounds good to me then. He made a sound argument for using standard2.0.

**Comment by lukevp** [comment]
@robotdan let me know if you need me to pull latest master into this PR and resolve conflicts.

**Comment by robotdan** [comment]
Thanks @lukevp I can merge it in ok I think.

**Comment by robotdan** [comment]
The only change I made was to use 

```
patchRequest.RequestUri = new Uri(requestUri, UriKind.RelativeOrAbsolute);
```

instead of 

```
patchRequest.RequestUri = new Uri(requestUri, UriKind.Relative);
```

I stepped through the `PostAsync` code and it was using `RelativeOrAbsolute` - not sure it matters in this case or not.

**Pull request merged**
